name = "BicubicSplines"
uuid = "2002e34d-a8f4-4a1f-ad31-768c4e97a8ee"
version = "0.1.0"
authors = ["Adnan Muradbegović <amuradbego1@etf.unsa.ba>", "Irhad Breščić <ibrescic1@etf.unsa.ba>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
